// Generated by dts-bundle v0.4.3

declare module 'phoenix-odata' {
    export { $filter2mongoFilter, $aggregation2mongoAggregation } from 'phoenix-odata/lib/mongodb/odata-filter';
    export { queryOptions, queryResult, parseSelect, applySelect } from 'phoenix-odata/lib/mongodb/odata';
}

declare module 'phoenix-odata/lib/mongodb/odata-filter' {
    export function $filter2mongoFilter(filter: string, schema?: any): any;
    export function $aggregation2mongoAggregation(aggregation: string, groupby: string, schema?: any): any;
}

declare module 'phoenix-odata/lib/mongodb/odata' {
    export function queryResult(payload: any[], count?: number): any;
    export function parseSelect(select?: string): string[];
    export function applySelect(payload: any, select: string[]): any;
    export function queryOptions(query: any): any;
}

